x1 = float(input("Введите x1: "))
y1 = float(input("Введите y1: "))
x2 = float(input("Введите x2: "))
y2 = float(input("Введите y2: "))
w = abs(x2 - x1)
h = abs(y2 - y1)
p = 2 * (w + h)
s = w * h
print(f"Периметр прямоугольника: {p}")
print(f"Площадь прямоугольника: {s}")
